[workspace]
authors = ["Thomas Li <thomasli@ust.hk>"]
channels = ["conda-forge"]
name = "signify-app-deployment"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
start = "supervisorctl -c supervisord.conf start all"
stop = "supervisorctl -c supervisord.conf stop all"
supervisorctl = "supervisorctl -c supervisord.conf"
supervisord = "supervisord -c supervisord.conf"

[dependencies]
redis-server = ">=7.4.0,<8"
caddy = ">=2.10.0,<3"
supervisor = ">=4.2.5,<5"
